# Generated by Django 5.2.3 on 2025-06-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('credor_doc', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Documento do Credor (CNPJ/CPF)')),
                ('credor_nome', models.CharField(max_length=255, verbose_name='Nome do Credor')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato_n', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número do Contrato')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credor', verbose_name='Credor')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('fatura_n', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número da Fatura')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contrato', verbose_name='Contrato')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credor', verbose_name='Credor')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('nf_n', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número da NF')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contrato', verbose_name='Contrato')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credor', verbose_name='Credor')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período de Referência')),
                ('grupo', models.IntegerField(blank=True, null=True, verbose_name='Grupo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contrato', verbose_name='Contrato')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credor', verbose_name='Credor')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fatura', verbose_name='Fatura')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notafiscal', verbose_name='Nota Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrato')),
                ('produto_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produtoservico', verbose_name='Produto/Serviço')),
            ],
            options={
                'unique_together': {('contrato', 'produto_servico')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='itens',
            field=models.ManyToManyField(through='core.ItemContrato', to='core.produtoservico', verbose_name='Itens do Contrato'),
        ),
    ]
